services:
    nginx:
        image: nginx:1.27.0-alpine-slim
        volumes:
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
            - ./:/var/www
        ports:
            - '${APP_PORT:-80}:80'
        restart: always
        depends_on:
            - app
        container_name: my-store_nginx

    app:
        image: ${APP_IMAGE}
        environment:
          APP_URL: '${APP_URL}'
          DB_CONNECTION: '${DB_CONNECTION}'
          DB_HOST: '${DB_HOST}'
          DB_PASSWORD: '${secrets.DB_PASSWORD}'
        volumes:
            - ./:/var/www
        ports:
            - '${VITE_PORT:-5173}:5173'
        depends_on:
            - db
        container_name: my-store_app

    db:
        image: postgres:16.3-alpine3.20
        restart: always
        volumes:
            - ./var/tmp/db:/var/lib/pgsql
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - '${DB_PORT:-5432}:5432'
        container_name: my-store_db


