[program:jobs-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work redis --queue=default,jobs --tries=3 --sleep=3
autostart=true
autorestart=true
user=root
numprocs=4
redirect_stderr=true
