name: ci-cd
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/bake-action@v5
        with:
          push: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm run build

